### ISSUE TITLE
로고 마지막 문자 가려지는 문제

### ISSUE THREAD

**Issue by jwChung** [Publyto/web-for-ico#16]
마지막 O 자가 반쯤 가려지네요. 

![image](https://user-images.githubusercontent.com/3784448/41827620-54bc9b94-786b-11e8-9331-835245c1dd8a.png)

@MoonsooJ

**Comment by jwChung** [comment]
@hoonisherepublyto 원본 그림이 그러네요. 의도하신 건가요? @MoonsooJ

**Comment by MoonsooJ** [comment]
@jwChung 
logo.svg 파일 width 값 변경하여 해결했었는데 정렬 업데이트 하면서 바뀐 것 같네요. 다시 수정했습니다. 

@hoonisherepublyto 
사파리 브라우저에서만 잘림 현상이랑 폰트가 달리 보이는 증상이 있네요. 해당 값만 수정한 터라 전체 레이아웃에 영향을 줄 수도 있으니 확인해 주세요.

**Comment by hoonisherepublyto** [comment]
아마 로고 SVG에 들어간 폰트가 아웃라인이 되있지 않아서 그런거같습니다.

**Comment by jwChung** [comment]
두 분다 수정하셨네요. 이슈 닫겠습니다.
